
services:
  mongo:
    image: mongo:latest
    container_name: aluguel-veiculo
    ports:
      - "27017:27017"
    command: mongod --storageEngine wiredTiger --bind_ip_all
    volumes:
      - mongo_data:/data/db
    networks:
      - aluguelVeiculo_network

  minio:
    image: minio/minio:latest
    container_name: aluguel-veiculo-bucket
    ports:
      - "9000:9000"  
      - "9001:9001"  
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - aluguelVeiculo_network

  api:
    build: .
    container_name: aluguel-veiculo-api
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./app:/app/app
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    depends_on:
      - mongo
      - minio
    networks:
      - aluguelVeiculo_network

volumes:
  mongo_data:   
  minio_data: 

networks:
  aluguelVeiculo_network:  
    driver: bridge